proxy:
  secretToken: "<RANDOM_HEX>"

# Jupyter lab is default
singleuser:
  defaultUrl: "/lab"
  image:
    name: jupyter/minimal-notebook
    tag: d4cbf2f80a2a
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:d4cbf2f80a2a
        
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
      
cull:
  enabled: false
  #timeout: <max-idle-seconds-before-user-pod-is-deleted>
  #every: <number-of-seconds-this-check-is-done>

auth:
  admin:
    users:
      - christian_adm
  type: dummy
  dummy:
    password: "<DUMMY_PW>"
  whitelist:
    users:
      - christian_adm
      - christian_1
      - christian_2
      - christian_3
      - christian_4
      - abhijay
      - andreas
      - anubhav
      - herbert
      - johannes
      - lijo 
      - miko
      - paula
      - sandra
